version: '3'

services:
    web:
        build:
            context: .
        environment:
            - DB_HOST=mysql
            - DB_USERNAME=root 
            - DB_PASSWORD=customer
            - DB_PORT=3306
            - DB_NAME=customer
        ports:
            - "80:4300"
        restart: always
        depends_on: 
            - "mysql"
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=customer
        expose:
            - "3306"