version: '2'

services:
  web:
    build: .
    ports:
      - "3030:3030"
    links:
      - mysql
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: nodejs
      PORT: 3030
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306"